global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus-prod:9090"]

  - job_name: "Spring Boot Application"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 2s
    scheme: http
    static_configs:
      - targets: ["ims-backend:8080"]
        labels:
          application: "Bento"

  - job_name: "grafana"
    scrape_interval: 15s
    static_configs:
      - targets: ["grafana-prod:3000"]
        labels:
          application: "Grafana"

  - job_name: "traefik"
    scrape_interval: 15s
    static_configs:
      - targets: ["traefik-proxy:8080"]
        labels:
          application: "Traefik"
