services:
  ims-backend:
    container_name: ims-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - ${IMS_BACKEND_PORT:-8080}:8080
    volumes:
      - ./.env:/app/.env
    depends_on:
      - postgres
    profiles:
      - prod

  postgres:
    container_name: ims-database
    image: postgres
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ~/ims-pgsql:/var/lib/postgresql/data
    profiles:
      - dev
      - prod

  keycloak:
    container_name: keycloak-auth
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:-localhost}
      KC_HOSTNAME_PORT: ${KEYCLOAK_PORT:-7080}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm.json
    ports:
      - "${KEYCLOAK_PORT:-7080}:${KEYCLOAK_PORT:-7080}"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://${KEYCLOAK_HOSTNAME:-localhost}:${KEYCLOAK_PORT:-7080}/health/ready",
        ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      ["start-dev", "--http-port", "${KEYCLOAK_PORT:-7080}", "--import-realm"]
    volumes:
      - ${KEYCLOAK_VOLUME_PATH}:/opt/keycloak/data
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    profiles:
      - dev
      - prod

  postgres-test:
    container_name: ims-database-test
    image: postgres
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    profiles:
      - test

  keycloak-test:
    container_name: keycloak-auth-test
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:-localhost}
      KC_HOSTNAME_PORT: ${KEYCLOAK_PORT:-7080}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm.json
    ports:
      - "${KEYCLOAK_PORT:-7080}:${KEYCLOAK_PORT:-7080}"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://${KEYCLOAK_HOSTNAME:-localhost}:${KEYCLOAK_PORT:-7080}/health/ready",
        ]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      ["start-dev", "--http-port", "${KEYCLOAK_PORT:-7080}", "--import-realm"]
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    profiles:
      - test
