services:
  ims-backend:
    container_name: ims-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres
    profiles:
      - prod

  postgres:
    container_name: ims-database
    image: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ~/ims-pgsql:/var/lib/postgresql/data
    profiles:
      - dev
      - prod
