name: Main Pipeline

on:
  push:
    branches: [main, traefik]
  pull_request:
    branches: [main, traefik]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build-and-push:
    name: Build and Push Docker Images
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit

  playwright-tests:
    name: Run Playwright Tests
    needs: build-and-push
    if: ${{ always() && needs.build-and-push.result == 'success' }}
    uses: ./.github/workflows/playwright.yml
    secrets: inherit

  deploy:
    name: Deploy to Production
    needs: [build-and-push, playwright-tests]
    if: ${{ always() && needs.playwright-tests.result == 'success' && needs.build-and-push.result == 'success' && github.event_name != 'pull_request' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
